// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgMshUjnUdKw52breIVSOJcm3gv43hJo',
    appId: '1:160286679537:web:c00de5b3604e1723d0a450',
    messagingSenderId: '160286679537',
    projectId: 'exponomade-42671',
    authDomain: 'exponomade-42671.firebaseapp.com',
    storageBucket: 'exponomade-42671.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjgeaVDYP755R20EgM1OgAkS2LK_CcvSI',
    appId: '1:160286679537:android:961fc3e361cfc16dd0a450',
    messagingSenderId: '160286679537',
    projectId: 'exponomade-42671',
    storageBucket: 'exponomade-42671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxaxjbCoJZHjdeAFfY-P3mzrYJHPFc0k',
    appId: '1:160286679537:ios:8f511c2062123432d0a450',
    messagingSenderId: '160286679537',
    projectId: 'exponomade-42671',
    storageBucket: 'exponomade-42671.appspot.com',
    iosClientId: '160286679537-mfjrsbj64dvil4slq0m722707o22pmg5.apps.googleusercontent.com',
    iosBundleId: 'ch.hevs.expoNomadeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxaxjbCoJZHjdeAFfY-P3mzrYJHPFc0k',
    appId: '1:160286679537:ios:752f8b32f06ae54dd0a450',
    messagingSenderId: '160286679537',
    projectId: 'exponomade-42671',
    storageBucket: 'exponomade-42671.appspot.com',
    iosClientId: '160286679537-ppnkllmnci684ndb0tp10l9scab15j0n.apps.googleusercontent.com',
    iosBundleId: 'ch.hevs.expoNomadeMobile.RunnerTests',
  );
}
